baseURL = "https://squirrel.quest/"
languageCode = "en-gb"
title = "EPA Notes"
theme = "hugo-book"

enableGitInfo = true

disableKinds = ["taxonomy", "taxonomyTerm"]

[params]
  BookTheme = "auto"
  BookComments = false
  BookRepo = "https://github.com/jake-walker/epanotes"
  BookCommitPath = "commit"

[markup.goldmark.renderer]
  unsafe = true
